[env]

## TERRAFORM BACKEND
TF_CLI_ARGS_init="-backend-config='bucket={{ env.PROJECT_ID }}-terraform-state' -backend-config='prefix={{ env.PROJECT_NAME }}/{{ env.ENVIRONMENT }}'"

# TERRAFORM INPUTS
TF_VAR_environment = "{{ env.ENVIRONMENT }}"
TF_VAR_project_name = "{{ env.PROJECT_NAME }}"
TF_VAR_project_id = "{{ env.PROJECT_ID }}"
TF_VAR_region = "{{ env.REGION }}"
TF_VAR_db_tier = "db-f1-micro"
TF_VAR_default_schema = "sandbox"
TF_VAR_liquibase_schema = "liquibase"

[tools]
terraform = "1.13.4"